gText_Birch_Welcome::
# 1 "data/text/birch_speech.pory"
	.string "Hello and welcome to the world of\n"
	.string "POKéMON!\p"
	.string "My name is FRITZ but everyone knows me\n"
	.string "as the HACK DEVELOPER.\p"
	.string "$"

gText_Birch_Pokemon::
# 5 "data/text/birch_speech.pory"
	.string "You of course know of “POKéMON.”\p"
	.string "$"

gText_Birch_MainSpeech::
# 9 "data/text/birch_speech.pory"
	.string "I just wanted to say thank you for\n"
	.string "making this possible and helping Light\l"
	.string "with the charity he ran! It's was\l"
	.string "exciting seeing how far the event went\l"
	.string "and getting this unlocked! So let's skip\l"
	.string "ahead shall we?\p"
	.string "$"

gText_Birch_AndYouAre::
# 13 "data/text/birch_speech.pory"
	.string "Who's taking on the adventure today?\p"
	.string "$"

gText_Birch_BoyOrGirl::
# 17 "data/text/birch_speech.pory"
	.string "BRENDAN or MAY?\p"
	.string "$"

gText_Birch_WhatsYourName::
# 21 "data/text/birch_speech.pory"
	.string "All right. What's your name?\p"
	.string "$"

gText_Birch_SoItsPlayer::
# 26 "data/text/birch_speech.pory"
	.string "So it's {PLAYER}{KUN}?\p"
	.string "$"

gText_Birch_YourePlayer::
# 31 "data/text/birch_speech.pory"
	.string "Ah, so {PLAYER}{KUN} will be the lead today!\p"
	.string "$"

gText_Birch_AreYouReady::
# 35 "data/text/birch_speech.pory"
	.string "Last note before we begin! I did my\n"
	.string "best to match pics to trainers!\l"
	.string "Apologies if it's not a great match! All\l"
	.string "right, are you ready? Your very own\l"
	.string "adventure is about to unfold!\p"
	.string "$"
