gText_Birch_Welcome::
	.string "Hello and welcome to the world of\n"
	.string "POKéMON!\p"
	.string "My name is FRITZ.\p"
	.string "But everyone knows me as the HACK\n"
	.string "DEVELOPER.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "You of course know of “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I just wanted to say thank you for\n"
	.string "making this possible and helping Light\l"
	.string "with the charity he ran!\p"
	.string "It's was exciting seeing how far the\n"
	.string "the event went and getting this\l"
	.string "unlocked!\p"
	.string "So let's skip ahead shall we?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Who's taking on the adventure today?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "BRENDAN or MAY?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, so {PLAYER}{KUN} will be the lead\n"
	.string "today!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Last note before we begin!\p"
	.string "I did my best to match pics to\n"
	.string "trainers! Apologies if it's not a\l"
	.string "great match!\p"
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold!\p"
	.string "$"
