gText_Birch_Welcome::
	.string "Hello and welcome to the world of\n"
	.string "POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "But you knew that already didn't you?\p"
	.string "I just wanted to say thank you for\n"
	.string "making this possible and helping Light\l"
	.string "with the charity he ran!\p"
	.string "It's was exciting seeing how far the\n"
	.string "the event went and getting this\l"
	.string "unlocked!\p"
	.string "So let's skip ahead shall we?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Who's taking on the adventure today?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "BRENDAN or MAY?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, so {PLAYER}{KUN} will be the lead\n"
	.string "today!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold!\p"
	.string "$"
