# 1 "data/text/check_furniture.pory"
Text_PictureBookShelf:
# 2 "data/text/check_furniture.pory"
	.string "There's a set of POKéMON picture books.$"
# 3 "data/text/check_furniture.pory"

# 4 "data/text/check_furniture.pory"
Text_BookShelf:
# 5 "data/text/check_furniture.pory"
	.string "It's filled with all sorts of books.$"
# 6 "data/text/check_furniture.pory"

# 7 "data/text/check_furniture.pory"
Text_Vase:
# 8 "data/text/check_furniture.pory"
	.string "This vase looks expensive…\n"
# 9 "data/text/check_furniture.pory"
	.string "Peered inside…\p"
# 10 "data/text/check_furniture.pory"
	.string "But, it was empty.$"
# 11 "data/text/check_furniture.pory"

# 12 "data/text/check_furniture.pory"
Text_EmptyTrashCan:
# 13 "data/text/check_furniture.pory"
	.string "It's empty.$"
# 14 "data/text/check_furniture.pory"

# 15 "data/text/check_furniture.pory"
Text_ShopShelf:
# 16 "data/text/check_furniture.pory"
	.string "The shelves brim with all sorts of\n"
# 17 "data/text/check_furniture.pory"
	.string "POKéMON merchandise.$"
# 18 "data/text/check_furniture.pory"

# 19 "data/text/check_furniture.pory"
Text_Blueprint:
# 20 "data/text/check_furniture.pory"
	.string "A blueprint of some sort?\n"
# 21 "data/text/check_furniture.pory"
	.string "It's too complicated!$"

Text_PokemonCenterBookShelf::
# 23 "data/text/check_furniture.pory"
	.string "There's a book about how to dragons in\n"
	.string "here. Seems odd for a POKéCENTER\l"
	.string "though.$"
